### ISSUE TITLE
NumberFormatException: Invalid float for certain SVGs

### ISSUE THREAD

**Issue by teslacoil** [inloop/svg2android#4] opened 2015-01-09 19:26 UTC
Some SVGs remove spaces between floating point numbers that start with a "." (eg "1.11.89" is two floats, 1.11 and .89). Android does not handle this. It can be fixed by adding spaces (eg "1.11 .89").

Example https://github.com/google/material-design-icons/blob/master/av/svg/production/ic_play_shopping_bag_24px.svg

See https://stackoverflow.com/questions/27561170/vectordrawable-causes-numberformatexception

**Comment by eboye** [comment] 2015-01-13 02:31
After path replace line https://github.com/inloop/svg2android/blob/gh-pages/js/main.js#L155

I've added this code:

<code>path = path.replace(/(\ |-)./g, " 0.");</code>

and it works flawlessly :)

**Comment by yuraj11** [comment] 2015-01-13 10:29
Thanks for report.
eboye, that line was not working for me properly, i have added this:
`path = path.replace(/(\.\d+)(\.\d)/g, "\$1 \$2");`
It's pushed, could you test It guys?

**Comment by eboye** [comment] 2015-01-14 00:17
@yuraj11 yes, it does work :) Maybe I haven't covered all the situations with my regex.

Thanks for the fix.

I don't know if I should start a new issue, but when <group> is added, it always messes from which XY coordinate it should start for the second path. I don't know if this is fixable at all.

edit: the problem is with no fill path ... once removed everything works as expected ;)

**Comment by yuraj11** [comment] 2015-01-16 09:25
If there is another issue not related to this please create new issue.

**Comment by teslacoil** [comment] 2015-01-21 22:01
It seems that regex still doesn't work for some SVGs (looks like it might need to be run multiple times), such as https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_history_24px.svg :

Caused by: java.lang.NumberFormatException: Invalid float: ".07.14"

9H1l3.89 3.89.07.14L9 12H6c0-3.87

**Comment by yuraj11** [comment] 2015-01-23 10:35
Not sure, but I have tried changing It to `.07 .14` but got this weird result in preview:
![deformed_svg](https://cloud.githubusercontent.com/assets/5477518/5873129/98cdf8f6-a2f3-11e4-853a-69ac9d2f68b3.jpg)
android svg renderer bug or something else hm

**Comment by teslacoil** [comment] 2015-01-23 19:57
I noticed that too after changing it by hand. I'm guessing it's an android bug and not an issue with svg2android. We've had to manually tune some SVGs before converting them (not just converting polygons into paths, but sometimes fudging the paths a bit so they don't have completely straight lines)

**Comment by yuraj11** [comment] 2015-01-26 12:20
@teslacoil I have changed regex a bit so number format should be fixed now, please check It. We can create new issue for rendering bug and see If there is a workaround.

**Comment by yuraj11** [comment] 2015-01-26 13:48
found problem with weird rendering - It is bug in svg2android, I have tried changing M to m and was rendered correctly, must explore this.

**Edit:** https://github.com/inloop/svg2android/issues/8 fixed It :hammer: tried a few icons from /google/material-design-icons and It works fine

**Closed as completed** 2015-01-26 14:54 UTC

**Comment by snodnipper** [comment] 2016-03-08 11:11
https://code.google.com/p/android/issues/detail?id=202670

Reported the issue before establishing the cause (old graphics)
